FROM quay.io/keycloak/keycloak:26.3

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--optimized", "--http-enabled=true", "--proxy-headers=xforwarded"]
