FROM quay.io/keycloak/keycloak:26.3 AS builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_DB=postgres
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.3
COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY keycloak/themes/giga-desk /opt/keycloak/themes/giga-desk

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--optimized", "--http-enabled=true", "--proxy-headers=xforwarded"]
