$ErrorActionPreference = 'Stop'
$runtime = if ([string]::IsNullOrWhiteSpace($env:GIGA_DESK_WORKER_AGENT_TYPE)) { 'CodexAppServer' } else { $env:GIGA_DESK_WORKER_AGENT_TYPE }
if ($runtime -notin @('CodexAppServer', 'CodexSdk', 'ClaudeAgentSdk')) { throw 'GIGA_DESK_WORKER_AGENT_TYPE must be CodexAppServer, CodexSdk, or ClaudeAgentSdk.' }
if ($runtime -ne 'ClaudeAgentSdk' -and $null -eq (Get-Command codex -ErrorAction SilentlyContinue)) { throw 'Codex must be installed and authenticated.' }
if ($runtime -eq 'ClaudeAgentSdk' -and [string]::IsNullOrWhiteSpace($env:ANTHROPIC_API_KEY)) { throw 'ANTHROPIC_API_KEY must be set for Claude Agent SDK.' }
foreach ($command in @('node', 'npm', 'tar')) { if ($null -eq (Get-Command $command -ErrorAction SilentlyContinue)) { throw "Missing required command: $command" } }
$configDir = Join-Path $env:USERPROFILE '.config\giga-desk'; $agentFile = Join-Path $configDir 'agent.env.ps1'; $workerFile = Join-Path $configDir 'worker.env.ps1'; $taskDir = Join-Path $configDir 'task'; $runnerFile = Join-Path $taskDir 'run-worker.ps1'; $releaseRoot = Join-Path $env:LOCALAPPDATA 'GigaDesk\worker'; $taskName = 'Giga Desk Codex Worker'; $backup = Join-Path ([IO.Path]::GetTempPath()) "giga-desk-worker-backup-$([guid]::NewGuid())"; $committed = $false
New-Item -ItemType Directory -Force -Path $backup | Out-Null
if (Test-Path $configDir) { Copy-Item -Recurse -Force $configDir (Join-Path $backup 'config') }; if (Test-Path $releaseRoot) { Copy-Item -Recurse -Force $releaseRoot (Join-Path $backup 'release') }; $previousTask = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue; if ($null -ne $previousTask) { Export-ScheduledTask -TaskName $taskName | Set-Content -NoNewline (Join-Path $backup 'task.xml') }
try {
  if (Test-Path $agentFile) { . $agentFile }; foreach ($name in @('GIGA_DESK_AGENT_API_URL','GIGA_DESK_AGENT_NODE_ID','GIGA_DESK_AGENT_OIDC_TOKEN_URL','GIGA_DESK_AGENT_OIDC_CLIENT_ID','GIGA_DESK_AGENT_OIDC_CLIENT_SECRET')) { if ([string]::IsNullOrWhiteSpace([Environment]::GetEnvironmentVariable($name))) { throw "Missing $name." } }
  $releaseUrl = if ([string]::IsNullOrWhiteSpace($env:GIGA_DESK_WORKER_RELEASE_URL)) { "$(([uri]$env:GIGA_DESK_AGENT_API_URL).GetLeftPart([UriPartial]::Authority))/releases/giga-desk-worker.tgz" } else { $env:GIGA_DESK_WORKER_RELEASE_URL }; $download = Join-Path ([IO.Path]::GetTempPath()) "giga-desk-worker-$([guid]::NewGuid())"; New-Item -ItemType Directory -Force -Path $download | Out-Null
  try { $archive = Join-Path $download 'worker.tgz'; Invoke-WebRequest -Uri $releaseUrl -OutFile $archive; Invoke-WebRequest -Uri "$releaseUrl.sha256" -OutFile "$archive.sha256"; $expected = (Get-Content "$archive.sha256" -Raw).Split([char[]]' ')[0]; $actual = (Get-FileHash $archive -Algorithm SHA256).Hash.ToLowerInvariant(); if ($expected.ToLowerInvariant() -ne $actual) { throw 'Worker checksum mismatch.' }; $stage = Join-Path $releaseRoot ".staging-$actual"; $final = Join-Path $releaseRoot "releases\$actual"; Remove-Item -Recurse -Force $stage -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Force -Path $stage | Out-Null; & tar -xzf $archive -C $stage; Push-Location $stage; & npm install --omit=dev --no-audit --no-fund; if ($LASTEXITCODE -ne 0) { throw 'Worker SDK dependency installation failed.' }; Pop-Location; New-Item -ItemType Directory -Force -Path (Split-Path $final) | Out-Null; if (-not (Test-Path $final)) { Move-Item $stage $final } } finally { Remove-Item -Recurse -Force $download -ErrorAction SilentlyContinue }
  New-Item -ItemType Directory -Force -Path $taskDir | Out-Null; $safe = { param($value) $value.Replace("'", "''") }; $utf8 = [Text.UTF8Encoding]::new($false); [IO.File]::WriteAllText($agentFile, "`$env:GIGA_DESK_AGENT_API_URL = '$(& $safe $env:GIGA_DESK_AGENT_API_URL)'`n`$env:GIGA_DESK_AGENT_NODE_ID = '$(& $safe $env:GIGA_DESK_AGENT_NODE_ID)'`n`$env:GIGA_DESK_AGENT_OIDC_TOKEN_URL = '$(& $safe $env:GIGA_DESK_AGENT_OIDC_TOKEN_URL)'`n`$env:GIGA_DESK_AGENT_OIDC_CLIENT_ID = '$(& $safe $env:GIGA_DESK_AGENT_OIDC_CLIENT_ID)'`n`$env:GIGA_DESK_AGENT_OIDC_CLIENT_SECRET = '$(& $safe $env:GIGA_DESK_AGENT_OIDC_CLIENT_SECRET)'`n`$env:ANTHROPIC_API_KEY = '$(& $safe $env:ANTHROPIC_API_KEY)'`n", $utf8); [IO.File]::WriteAllText($workerFile, "`$env:GIGA_DESK_WORKER_AGENT_TYPE = '$runtime'`n`$env:GIGA_DESK_WORKER_MODEL_IDENTIFIER = '$(& $safe $env:GIGA_DESK_WORKER_MODEL_IDENTIFIER)'`n`$env:GIGA_DESK_WORKER_REPOSITORIES = '[]'`n`$env:GIGA_DESK_AGENT_POLL_INTERVAL_MS = '5000'`n`$env:GIGA_DESK_AGENT_HEARTBEAT_INTERVAL_MS = '30000'`n", $utf8)
  $runner = "`$ErrorActionPreference = 'Stop'`n. '$agentFile'`n. '$workerFile'`nSet-Location -LiteralPath '$final'`n& '$(Get-Command node | Select-Object -ExpandProperty Source)' apps/codex-worker/dist/main.js`n"; [IO.File]::WriteAllText($runnerFile, $runner, $utf8); Unregister-ScheduledTask -TaskName $taskName -Confirm:`$false -ErrorAction SilentlyContinue; $identity = [Security.Principal.WindowsIdentity]::GetCurrent().Name; $action = New-ScheduledTaskAction -Execute "$PSHOME\powershell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$runnerFile`""; Register-ScheduledTask -TaskName $taskName -Action $action -Trigger (New-ScheduledTaskTrigger -AtLogOn -User $identity) -Principal (New-ScheduledTaskPrincipal -UserId $identity -LogonType Interactive -RunLevel Limited) -Force | Out-Null; Start-ScheduledTask -TaskName $taskName; if ((Get-ScheduledTask -TaskName $taskName).State -eq 'Disabled') { throw 'Worker task did not activate.' }; $committed = $true; Write-Host "$runtime worker installed and active."
} finally { if (-not $committed) { Unregister-ScheduledTask -TaskName $taskName -Confirm:`$false -ErrorAction SilentlyContinue; Remove-Item -Recurse -Force $configDir,$releaseRoot -ErrorAction SilentlyContinue; if (Test-Path (Join-Path $backup 'config')) { Move-Item (Join-Path $backup 'config') $configDir }; if (Test-Path (Join-Path $backup 'release')) { Move-Item (Join-Path $backup 'release') $releaseRoot }; if (Test-Path (Join-Path $backup 'task.xml')) { Register-ScheduledTask -TaskName $taskName -Xml (Get-Content (Join-Path $backup 'task.xml') -Raw) | Out-Null }; Write-Error 'Installation failed; the prior Giga Desk worker was restored.' }; Remove-Item -Recurse -Force $backup -ErrorAction SilentlyContinue }
