import { Link } from 'react-router-dom';
import { useAuthenticatedLoad } from '../hooks/use-authenticated-load.js';
import { fetchProjects, type ProjectSummary } from '../project-api.js';
import { statusClassName } from '../ui/status-class-name.js';
import { buttonVariants } from '@/components/ui/button';

export function ProjectListPage() {
  const { data: projects, error } = useAuthenticatedLoad<ProjectSummary>(fetchProjects);

  return <><header className="page-header control-center-header"><div><p className="eyebrow">01 — Workspace overview</p><h1>Project Portfolio</h1><p>Track delivery health, priorities, and active development work.</p></div><div className="page-header-actions"><span className="environment-chip"><i aria-hidden="true" />Production workspace</span></div></header><section className="project-command" aria-label="Project commands"><span>Project registry</span><Link className={buttonVariants()} to="/projects/new">Add project</Link></section>{error ? <p className="state-panel" role="alert">{error}</p> : projects === null ? <p className="state-panel">Loading projects…</p> : projects.length === 0 ? <p className="state-panel">No projects yet. Add your first project above.</p> : <><section className="dashboard-section" aria-labelledby="portfolio-health"><div className="section-heading"><p className="section-kicker">02 — System health</p><h2 id="portfolio-health">Portfolio at a glance</h2></div><div className="summary-stats" aria-label="Portfolio summary"><div className="summary-stat"><span className="summary-stat-label">Total projects</span><span className="summary-stat-value">{projects.length}</span></div><div className="summary-stat"><span className="summary-stat-label">Active</span><span className="summary-stat-value accent-green">{projects.filter((project) => project.status === 'Active').length}</span></div><div className="summary-stat"><span className="summary-stat-label">High priority</span><span className="summary-stat-value accent-amber">{projects.filter((project) => project.priority === 'High').length}</span></div></div></section><section aria-label="Projects" className="dashboard-section project-section"><div className="section-heading"><div><p className="section-kicker">03 — Active projects</p><h2>Delivery work</h2></div></div><div className="grid project-grid">{projects.map((project) => <article className="card project-row" key={project.id}><div className="card-header"><div><span className="project-key">{project.key}</span><h2><Link to={`/projects/${project.id}`}>{project.key} · {project.name}</Link></h2></div><span className={statusClassName(project.status)}>{project.status}</span></div><p>{project.businessGoal}</p><div className="status-row"><div className="status-item"><span className="status-label">Priority</span><span className="status-value">{project.priority}</span></div><div className="status-item"><span className="status-label">Updated</span><span className="status-value">{new Date(project.updatedAt).toLocaleDateString()}</span></div></div></article>)}</div></section></>}</>;
}
